# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- task: SendEmail@1
  inputs:
    To: 'ankit.kumar@infostride.com'
    CC: 'saurav.sharma@infostride.com'
    From: 'ithubchandigarh@gmail.com'
    Subject: 'pipleine'
    Body: 'Hi, Your Build is successful.'
    BodyAsHtml: false
    AddAttachment: false
    SmtpServer: 'smtp.gmail.com'
    SmtpPort: '465'
    SmtpUsername: 'ithubchandigarh@gmail.com'
    SmtpPassword: 'aveqavpvynpsirhi'