# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: SendEmail@1
  inputs:
    To: 'ankit.kumar@infostride.com'
    CC: 'saurav.sharma@infostride.com'
    From: 'ankit.kumar@infostride.com'
    Subject: 'pipleine'
    Body: 'Hi, Your Build is successful.'
    BodyAsHtml: false
    AddAttachment: true
    Attachment: '$(System.DefaultWorkingDirectory)/allure-report/history/**.json'
    SmtpServer: 'smtp.office365.com'
    SmtpUsername: 'ankit.kumar@infostride.com'
    SmtpPassword: 'INFO7184@Ak'