# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# - task: EmailReport@1
#   inputs:
#     sendMailConditionConfig: 'Always'
#     subject: '[{environmentStatus}] {passPercentage} tests passed in $(Release.EnvironmentName) stage for $(Build.BuildNumber)'
#     includeInToSectionStr: '1'
#     toAddress: 'aayush.khandelwal@infostride.com'
#     includeInCcSectionStr: '1'
#     ccAddress: 'saurav.sharma@infostride.com'
#     defaultDomain: 'microsoft.com'
#     groupTestResultsBy: 'run'
#     includeCommits: true
#     maxTestFailuresToShow: '15'
#     includeOthersInTotal: true
#     usePreviousEnvironment: false
#     smtpConnectionEndpoint: '465'

- task: EmailReport@1
  inputs:
    sendMailConditionConfig: 'Always'
    subject: '[{environmentStatus}] {passPercentage} tests passed in $(Release.EnvironmentName) stage for $(Build.BuildNumber)'
    toAddress: 'ankit.kumar@infostride.com'
    includeInCcSectionStr: '1'
    ccAddress: 'saurav.sharma@infostride.com'
    defaultDomain: 'microsoft.com'
    groupTestResultsBy: 'run'
    includeCommits: true
    maxTestFailuresToShow: '15'
    includeOthersInTotal: true
    usePreviousEnvironment: false
    smtpConnectionEndpoint: 'INFOSMTP'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Send-MailMessage -From 'ankitkumar5184@outlook.com' 
      -To 'ankit.kumar@infostride.com', 'gulshan.kumar@infostride.com' 
      -Subject 'Sending the Attachment' 
      -Body "Forgot to send the attachment. Sending now." ./allure-report/index.html
      -Priority High 
      -DeliveryNotificationOption OnSuccess,OnFailure 
      -SmtpServer 'smtp.office365.com'


# - task: EmailReport@1
#   inputs:
#     sendMailConditionConfig: 'Always'
#     subject: '[{environmentStatus}] {passPercentage} tests passed in $(Release.EnvironmentName) stage for $(Build.BuildNumber)'
#     toAddress: 'aayush.khandelwal@infostride.com'
#     includeInCcSectionStr: '1'
#     ccAddress: 'saurav.sharma@infostride.com'
#     defaultDomain: 'microsoft.com'
#     groupTestResultsBy: 'run'
#     includeCommits: true
#     maxTestFailuresToShow: '15'
#     includeOthersInTotal: false
#     usePreviousEnvironment: false
#     enableTLS: true

# - task: SendEmail@1
#   inputs:
#     To: 'ankit.kumar@infostride.com'
#     CC: 'saurav.sharma@infostride.com'
#     BCC: 'aayush.khandelwal@infostride.com'
#     From: 'ankit.kumar@infostride.com'
#     Subject: 'pipleine'
#     Body: 'Hi, Your Build is successful.'
#     BodyAsHtml: false
#     AddAttachment: true
#     Attachment: '$(System.DefaultWorkingDirectory)/allure-report/index.html'
#     SmtpServer: 'smtp.office365.com'
#     SmtpUsername: 'ankit.kumar@infostride.com'
#     SmtpPassword: 'INFO7184@Ak'